import { formatMoney, type InvoiceStatus, type QuoteLineItem, type QuoteTotals } from '@truecode/shared';

export interface InvoiceLike {
  number: string;
  title: string;
  client: { name: string; email?: string; phone?: string; address?: string };
  propertyAddress?: string;
  lineItems: QuoteLineItem[];
  currency: string;
  taxRatePct: number;
  totals: QuoteTotals;
  amountPaid?: number;
  balance?: number;
  dueDate?: string;
  status: InvoiceStatus | string;
  notes?: string;
  createdAt?: string;
}

/** Branded, print-ready invoice → print dialog (Save as PDF). Zero deps. */
export function downloadInvoicePdf(inv: InvoiceLike, brand: { name: string; owner?: string; email?: string }): void {
  const win = window.open('', '_blank', 'width=900,height=1200');
  if (!win) return;
  const m = (n: number) => formatMoney(n, inv.currency);
  const rows = inv.lineItems
    .map((li) => `<tr><td>${li.description}${li.category ? `<div class="cat">${li.category}</div>` : ''}</td><td class="num">${li.quantity}</td><td class="num">${m(li.unitPrice)}</td><td class="num">${m(li.quantity * li.unitPrice)}</td></tr>`)
    .join('');
  const due = inv.dueDate ? new Date(inv.dueDate).toLocaleDateString() : '';
  win.document.write(`<!doctype html><html><head><meta charset="utf-8"/><title>${inv.number}</title>
<style>
  @page{margin:16mm}*{box-sizing:border-box}
  body{font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#1A1A1A;margin:0}
  .head{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #111;padding-bottom:16px;margin-bottom:24px}
  .brand{font-size:22px;font-weight:800}.brand .sub{font-size:12px;color:#6B6B6B;font-weight:400;margin-top:2px}
  .meta{text-align:right;font-size:12px;color:#6B6B6B}.meta .num{font-size:16px;font-weight:700;color:#111}
  .tag{display:inline-block;background:#111;color:#fff;border-radius:999px;padding:2px 10px;font-size:11px;text-transform:uppercase;letter-spacing:.08em}
  h1{font-size:20px;margin:0 0 16px}
  .parties{display:flex;gap:40px;margin-bottom:22px;font-size:13px}
  .parties .label{font-size:10px;text-transform:uppercase;letter-spacing:.12em;color:#9a9a9a;margin-bottom:4px}
  table{width:100%;border-collapse:collapse;font-size:13px}
  th{text-align:left;font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#6B6B6B;border-bottom:2px solid #eee;padding:8px 6px}
  th.num,td.num{text-align:right}td{padding:10px 6px;border-bottom:1px solid #f2f2f2}td .cat{font-size:10px;color:#9a9a9a}
  .totals{margin-left:auto;width:280px;margin-top:16px;font-size:13px}.totals tr td{border:none;padding:5px 6px}
  .totals .grand td{border-top:2px solid #111;font-size:16px;font-weight:800;padding-top:10px}
  .totals .due td{color:#1F9D6B;font-weight:700}
  .note{margin-top:26px;font-size:12px;color:#444}.foot{margin-top:36px;padding-top:12px;border-top:1px solid #eee;font-size:10px;color:#9a9a9a;text-align:center}
</style></head><body>
  <div class="head">
    <div class="brand">${brand.name}<div class="sub">${brand.owner ?? ''}${brand.email ? ` · ${brand.email}` : ''}</div></div>
    <div class="meta"><div class="num">INVOICE ${inv.number}</div>${inv.createdAt ? `<div>Issued ${new Date(inv.createdAt).toLocaleDateString()}</div>` : ''}${due ? `<div>Due ${due}</div>` : ''}<div class="tag">${inv.status}</div></div>
  </div>
  <h1>${inv.title}</h1>
  <div class="parties">
    <div><div class="label">Bill to</div><strong>${inv.client.name}</strong>${inv.client.email ? `<div>${inv.client.email}</div>` : ''}${inv.client.address ? `<div>${inv.client.address}</div>` : ''}</div>
    ${inv.propertyAddress ? `<div><div class="label">Property</div><strong>${inv.propertyAddress}</strong></div>` : ''}
  </div>
  <table><thead><tr><th>Description</th><th class="num">Qty</th><th class="num">Unit</th><th class="num">Amount</th></tr></thead><tbody>${rows}</tbody></table>
  <table class="totals">
    <tr><td>Subtotal</td><td class="num">${m(inv.totals.subtotal)}</td></tr>
    ${inv.totals.discountAmount > 0 ? `<tr><td>Discount</td><td class="num">− ${m(inv.totals.discountAmount)}</td></tr>` : ''}
    ${inv.totals.taxAmount > 0 ? `<tr><td>Tax (${inv.taxRatePct}%)</td><td class="num">${m(inv.totals.taxAmount)}</td></tr>` : ''}
    <tr class="grand"><td>Total</td><td class="num">${m(inv.totals.total)}</td></tr>
    ${inv.amountPaid ? `<tr><td>Paid</td><td class="num">− ${m(inv.amountPaid)}</td></tr>` : ''}
    ${typeof inv.balance === 'number' ? `<tr class="due"><td>Balance due</td><td class="num">${m(inv.balance)}</td></tr>` : ''}
  </table>
  ${inv.notes ? `<div class="note"><strong>Notes:</strong> ${inv.notes}</div>` : ''}
  <div class="foot">${brand.name} · ${inv.number} · Generated by CloseFlow Invoicing</div>
  <script>window.onload=function(){setTimeout(function(){window.print();},250);};</script>
</body></html>`);
  win.document.close();
}
