import { formatMoney, type QuoteDTO } from '@truecode/shared';

/**
 * Renders a branded, print-ready quote/proposal and opens the print dialog
 * (→ "Save as PDF"). Zero dependencies; the quote is already in memory.
 */
export function downloadQuotePdf(quote: QuoteDTO, brand: { name: string; owner?: string; email?: string }): void {
  const win = window.open('', '_blank', 'width=900,height=1200');
  if (!win) return;
  const m = (n: number) => formatMoney(n, quote.currency);
  const valid = quote.validUntil ? new Date(quote.validUntil).toLocaleDateString() : '';

  const rows = quote.lineItems
    .map(
      (li) =>
        `<tr><td>${li.description}${li.category ? `<div class="cat">${li.category}</div>` : ''}</td><td class="num">${li.quantity}</td><td class="num">${m(li.unitPrice)}</td><td class="num">${m(li.quantity * li.unitPrice)}</td></tr>`,
    )
    .join('');

  win.document.write(`<!doctype html><html><head><meta charset="utf-8"/>
<title>${quote.number} — ${quote.title}</title>
<style>
  @page { margin: 16mm; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color:#1A1A1A; margin:0; }
  .head { display:flex; justify-content:space-between; align-items:flex-start; border-bottom:3px solid #111; padding-bottom:16px; margin-bottom:24px; }
  .brand { font-size:22px; font-weight:800; }
  .brand .sub { font-size:12px; color:#6B6B6B; font-weight:400; margin-top:2px; }
  .meta { text-align:right; font-size:12px; color:#6B6B6B; }
  .meta .num { font-size:16px; font-weight:700; color:#111; }
  h1 { font-size:20px; margin:0 0 16px; }
  .parties { display:flex; gap:40px; margin-bottom:22px; font-size:13px; }
  .parties .label { font-size:10px; text-transform:uppercase; letter-spacing:.12em; color:#9a9a9a; margin-bottom:4px; }
  table { width:100%; border-collapse:collapse; font-size:13px; }
  th { text-align:left; font-size:10px; text-transform:uppercase; letter-spacing:.08em; color:#6B6B6B; border-bottom:2px solid #eee; padding:8px 6px; }
  th.num, td.num { text-align:right; }
  td { padding:10px 6px; border-bottom:1px solid #f2f2f2; }
  td .cat { font-size:10px; color:#9a9a9a; }
  .totals { margin-left:auto; width:280px; margin-top:16px; font-size:13px; }
  .totals tr td { border:none; padding:5px 6px; }
  .totals .grand td { border-top:2px solid #111; font-size:16px; font-weight:800; padding-top:10px; }
  .note { margin-top:26px; font-size:12px; color:#444; }
  .note .label { font-weight:700; }
  .foot { margin-top:36px; padding-top:12px; border-top:1px solid #eee; font-size:10px; color:#9a9a9a; text-align:center; }
  .pill { display:inline-block; background:#F4EEE7; border-radius:999px; padding:2px 10px; font-size:11px; text-transform:capitalize; }
</style></head><body>
  <div class="head">
    <div class="brand">${brand.name}<div class="sub">${brand.owner ?? ''}${brand.email ? ` · ${brand.email}` : ''}</div></div>
    <div class="meta"><div class="num">${quote.number}</div><div>Issued ${new Date(quote.createdAt).toLocaleDateString()}</div>${valid ? `<div>Valid until ${valid}</div>` : ''}<div class="pill">${quote.status}</div></div>
  </div>
  <h1>${quote.title}</h1>
  <div class="parties">
    <div><div class="label">Prepared for</div><strong>${quote.client.name}</strong>${quote.client.email ? `<div>${quote.client.email}</div>` : ''}${quote.client.phone ? `<div>${quote.client.phone}</div>` : ''}${quote.client.address ? `<div>${quote.client.address}</div>` : ''}</div>
    ${quote.propertyAddress ? `<div><div class="label">Property</div><strong>${quote.propertyAddress}</strong></div>` : ''}
  </div>
  <table>
    <thead><tr><th>Description</th><th class="num">Qty</th><th class="num">Unit</th><th class="num">Amount</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <table class="totals">
    <tr><td>Subtotal</td><td class="num">${m(quote.totals.subtotal)}</td></tr>
    ${quote.totals.discountAmount > 0 ? `<tr><td>Discount</td><td class="num">− ${m(quote.totals.discountAmount)}</td></tr>` : ''}
    ${quote.totals.taxAmount > 0 ? `<tr><td>Tax (${quote.taxRatePct}%)</td><td class="num">${m(quote.totals.taxAmount)}</td></tr>` : ''}
    <tr class="grand"><td>Total</td><td class="num">${m(quote.totals.total)}</td></tr>
  </table>
  ${quote.notes ? `<div class="note"><span class="label">Notes:</span> ${quote.notes}</div>` : ''}
  ${quote.terms ? `<div class="note"><span class="label">Terms:</span> ${quote.terms}</div>` : ''}
  <div class="foot">${brand.name} · ${quote.number} · Generated by CloseFlow Quotations</div>
  <script>window.onload=function(){ setTimeout(function(){ window.print(); }, 250); };</script>
</body></html>`);
  win.document.close();
}
